server:
  port: 8001
spring:
  application:
    name: provider-hystrix-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/up?serverTimezone=UTC
    username: root
    password: qweasd
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
  cloud:
    inetutils:
      timeout-seconds: 10
mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.yuan.bean
eureka:
  instance:
    instance-id: provider8001
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
       defaultZone: http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka

