server:
  port: 7002
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
       defaultZone: http://eureka7003.com:7003/eureka/
  instance:
    hostname: eureka7002.com
